SELECT A.AUTHOR_ID
     , B.AUTHOR_NAME
     , A.CATEGORY
     , SUM(A.PRICE * C.SALES_SUM) AS TOTAL_SALES
  FROM BOOK A
 INNER JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
 INNER JOIN (SELECT AA.BOOK_ID AS BOOK_ID
                  , SUM(AA.SALES) AS SALES_SUM
               FROM BOOK_SALES AA
              WHERE SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
                AND SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
              GROUP BY AA.BOOK_ID) C
    ON A.BOOK_ID = C.BOOK_ID
 GROUP BY A.AUTHOR_ID
        , B.AUTHOR_NAME
        , A.CATEGORY
 ORDER BY A.AUTHOR_ID
        , A.CATEGORY DESC