-- 코드를 입력하세요
SELECT A.USER_ID AS USER_ID
     , A.PRODUCT_ID AS PRODUCT_ID
  FROM ONLINE_SALE A
 GROUP BY A.USER_ID
        , A.PRODUCT_ID
HAVING COUNT(*) >= 2
 ORDER BY A.USER_ID ASC
        , A.PRODUCT_ID DESC