SELECT TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
     , A.PRODUCT_ID AS PRODUCT_ID
     , A.USER_ID AS USER_ID
     , A.SALES_AMOUNT AS SALES_AMOUNT
  FROM ONLINE_SALE A
 WHERE A.SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
   AND A.SALES_DATE < TO_DATE('2022-04-01', 'YYYY-MM-DD')
   
 UNION ALL
 
SELECT TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
     , A.PRODUCT_ID AS PRODUCT_ID
     , NULL AS USER_ID
     , A.SALES_AMOUNT AS SALES_AMOUNT
  FROM OFFLINE_SALE A
 WHERE A.SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
   AND A.SALES_DATE < TO_DATE('2022-04-01', 'YYYY-MM-DD')
   
 ORDER BY SALES_DATE
        , PRODUCT_ID
        , USER_ID