-- 코드를 입력하세요
SELECT A.ANIMAL_ID AS ANIMAL_ID
     , A.NAME AS NAME
  FROM (SELECT A.ANIMAL_ID AS ANIMAL_ID
             , B.NAME AS NAME
          FROM ANIMAL_INS A
         INNER JOIN ANIMAL_OUTS B
            ON A.ANIMAL_ID = B.ANIMAL_ID
         ORDER BY B.DATETIME - A.DATETIME DESC
       ) A
 WHERE ROWNUM <= 2