SELECT A.ANIMAL_ID
     , A.NAME
  FROM (SELECT B.ANIMAL_ID
             , B.NAME
          FROM ANIMAL_INS B
         INNER JOIN ANIMAL_OUTS C
            ON B.ANIMAL_ID = C.ANIMAL_ID
         ORDER BY C.DATETIME - B.DATETIME DESC) A
 WHERE ROWNUM <= 2