-- 코드를 입력하세요
SELECT A.CAR_ID AS CAR_ID
     , A.CAR_TYPE AS CAR_TYPE
     , FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
 INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
   AND B.DURATION_TYPE LIKE '30%'
 WHERE A.CAR_ID NOT IN (SELECT C.CAR_ID
                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                         WHERE C.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
                           AND C.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
                       )
   AND 500000 <= FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100)
   AND 2000000 >= FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100)
   AND A.CAR_TYPE IN ('세단', 'SUV')
 ORDER BY FEE DESC
        , A.CAR_TYPE 
        , A.CAR_ID DESC