-- 코드를 입력하세요
SELECT A.FOOD_TYPE AS FOOD_TYPE
     , A.REST_ID AS REST_ID
     , A.REST_NAME AS REST_NAME
     , A.FAVORITES AS FAVORITES
  FROM REST_INFO A
 INNER JOIN (SELECT A.FOOD_TYPE AS FOOD_TYPE
                  , MAX(A.FAVORITES) AS FAVORITES
               FROM REST_INFO A
              GROUP BY A.FOOD_TYPE
            ) B
    ON A.FOOD_TYPE = B.FOOD_TYPE
   AND A.FAVORITES = B.FAVORITES
 ORDER BY A.FOOD_TYPE DESC