-- 코드를 입력하세요
SELECT A.PRODUCT_ID AS PRODUCT_ID
     , A.PRODUCT_NAME AS PRODUCT_NAME
     , A.PRODUCT_CD AS PRODUCT_CD
     , A.CATEGORY AS CATEGORY
     , A.PRICE AS PRICE
  FROM FOOD_PRODUCT A
 WHERE A.PRICE = (SELECT MAX(A.PRICE) AS PRICE
                    FROM FOOD_PRODUCT A)