-- 코드를 입력하세요
SELECT A.HISTORY_ID AS HISTORY_ID
     , A.CAR_ID AS CAR_ID
     , TO_CHAR(A.START_DATE, 'YYYY-MM-DD') AS START_DATE
     , TO_CHAR(A.END_DATE, 'YYYY-MM-DD') AS END_DATE
     , CASE
        WHEN A.END_DATE - A.START_DATE + 1 >= 30
        THEN '장기 대여'
        ELSE '단기 대여'
       END AS RENT_TYPE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 WHERE TO_CHAR(A.START_DATE, 'YYYY-MM') = '2022-09'
 ORDER BY A.HISTORY_ID DESC