-- 코드를 입력하세요
SELECT A.CAR_ID AS CAR_ID
     , TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM9990.0') AS AVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 GROUP BY A.CAR_ID
HAVING ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
 ORDER BY ROUND(AVG(END_DATE - START_DATE + 1), 1) DESC
        , A.CAR_ID DESC