-- 코드를 입력하세요
SELECT A.CAR_TYPE AS CAR_TYPE
     , COUNT(*) AS CARS
  FROM CAR_RENTAL_COMPANY_CAR A
 WHERE OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%열선시트%'
    OR OPTIONS LIKE '%가죽시트%'
 GROUP BY A.CAR_TYPE
 ORDER BY A.CAR_TYPE