-- 코드를 입력하세요
SELECT A.APNT_NO AS APNT_NO
     , B.PT_NAME AS PT_NAME
     , A.PT_NO AS PT_NO
     , A.MCDP_CD AS MCDP_CD
     , C.DR_NAME AS DR_NAME
     , A.APNT_YMD AS APNT_YMD
  FROM APPOINTMENT A
 INNER JOIN PATIENT B
    ON A.PT_NO = B.PT_NO
 INNER JOIN DOCTOR C
    ON A.MDDR_ID = DR_ID
 WHERE TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
   AND A.APNT_CNCL_YN = 'N'
 ORDER BY A.APNT_YMD ASC
