SELECT H.HOUR
     , COUNT(A.ANIMAL_ID) AS CNT
  FROM (SELECT LEVEL - 1 AS HOUR
          FROM DUAL
        CONNECT BY LEVEL <= 24
       ) H
  LEFT JOIN ANIMAL_OUTS A
    ON TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) = H.HOUR
 GROUP BY H.HOUR
 ORDER BY H.HOUR