-- 코드를 입력하세요
SELECT A.DR_NAME AS DR_NAME
     , A.DR_ID AS DR_ID
     , A.MCDP_CD AS MCDP_CD
     , TO_CHAR(A.HIRE_YMD, 'YYYY-MM-DD') AS HIRE_YMD 
  FROM DOCTOR A
 WHERE MCDP_CD = 'CS'
    OR MCDP_CD = 'GS'
 ORDER BY HIRE_YMD DESC
        , DR_NAME ASC