SELECT A.MEMBER_ID
     , A.MEMBER_NAME
     , A.GENDER
     , TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE A
 WHERE A.TLNO IS NOT NULL
   AND TO_CHAR(A.DATE_OF_BIRTH, 'MM') = '03'
   AND A.GENDER = 'W'
 ORDER BY A.MEMBER_ID