-- 코드를 입력하세요
SELECT A.MEMBER_ID AS MEMBER_ID
     , A.MEMBER_NAME AS MEMBER_NAME
     , A.GENDER AS GENDER
     , TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE A
 WHERE TO_CHAR(A.DATE_OF_BIRTH, 'MM') = '03'
   AND A.TLNO IS NOT NULL
   AND A.GENDER = 'W'
 ORDER BY A.MEMBER_ID ASC