-- 코드를 입력하세요
SELECT B.USER_ID AS USER_ID
     , B.NICKNAME AS NICKNAME
     , SUM(A.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD A
 INNER JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
 WHERE A.STATUS = 'DONE'
HAVING SUM(A.PRICE) >= 700000
 GROUP BY B.USER_ID
        , B.NICKNAME
 ORDER BY TOTAL_SALES