-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(A.DATETIME,'HH24')) AS HOUR
     , COUNT(*) AS COUNT
  FROM ANIMAL_OUTS A
 WHERE TO_NUMBER(TO_CHAR(A.DATETIME,'HH24')) >= 9
   AND TO_NUMBER(TO_CHAR(A.DATETIME,'HH24')) < 20
 GROUP BY TO_CHAR(A.DATETIME,'HH24')
 ORDER BY HOUR