-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM A.START_DATE) AS MONTH
     , A.CAR_ID AS CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 INNER JOIN (SELECT AA.CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AA
              WHERE AA.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
              GROUP BY AA.CAR_ID
             HAVING COUNT(*) >= 5
            ) B
    ON A.CAR_ID = B.CAR_ID
 WHERE A.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
 GROUP BY EXTRACT(MONTH FROM A.START_DATE)
        , A.CAR_ID
 ORDER BY MONTH
        , A.CAR_ID DESC