-- 코드를 입력하세요
SELECT A.BOOK_ID AS BOOK_ID
     , TO_CHAR(A.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM BOOK A
 WHERE TO_CHAR(A.PUBLISHED_DATE, 'YYYY') = '2021'
   AND A.CATEGORY = '인문'
 ORDER BY A.PUBLISHED_DATE ASC