-- 코드를 입력하세요
SELECT '/home/grep/src/' || B.BOARD_ID || '/' || B.FILE_ID || B.FILE_NAME || B.FILE_EXT AS FILE_PATH
  FROM USED_GOODS_BOARD A
 INNER JOIN USED_GOODS_FILE B
    ON A.BOARD_ID = B.BOARD_ID
 WHERE A.VIEWS = (SELECT MAX(AA.VIEWS) AS VIEWS
                    FROM USED_GOODS_BOARD AA
                 )
 ORDER BY B.FILE_ID DESC