SELECT A.CATEGORY
     , SUM(B.SALES) AS TOTAL_SALES
  FROM BOOK A
 INNER JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
 WHERE B.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
   AND B.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
 GROUP BY A.CATEGORY
 ORDER BY A.CATEGORY